### ISSUE TITLE
Tracking: Feedback on Existing Modules

### ISSUE THREAD

**Issue by jkodroff** [pulumi/aws-training#35]
We have a decent amount of the content for the training written, but have only just assigned who's going to deliver it. We should get feedback in early to de-risk delivery:

- [ ] @tomweston to give @jkodroff feedback on Intro to K8s
- [ ] @tomweston to give @jkodroff feedback on #17 when complete (will add as a reviewer)
- [ ] @pierskarsenbarg to give @jkodroff feedback on #34 when complete (will add as a reviewer)
- [ ] @tomweston to give @desteves feedback on Intro to CI/CD
- [ ] @pierskarsenbarg to give @desteves feedback on ESC
- [ ] @jkodroff to give @desteves feedback on Advanced CI/CD (or just update the content)

Whoever is delivering the workshop ultimately owns the content (unless they explicitly do not want to, which is also fine), so please feel free to alter the material in whatever way you see fit if you're delivering the module.
